/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 treeHolidayPineSnowRound.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { snow } from "./materials"

type GLTFResult = GLTF & {
  nodes: {
    Mesh_treePineSnowRound: THREE.Mesh
    Mesh_treePineSnowRound_1: THREE.Mesh
    Mesh_treePineSnowRound_2: THREE.Mesh
  }
  materials: {
    leaves: THREE.MeshStandardMaterial
    snow: THREE.MeshStandardMaterial
    wood: THREE.MeshStandardMaterial
  }
}

export function TreeHolidayPineSnowRound(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/treeHolidayPineSnowRound.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_treePineSnowRound.geometry} material={materials.leaves} />
      <mesh geometry={nodes.Mesh_treePineSnowRound_1.geometry} material={snow} />
      <mesh geometry={nodes.Mesh_treePineSnowRound_2.geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/treeHolidayPineSnowRound.glb')
