/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 treeHolidayPineSnow.glb -t
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_treePineSnow: THREE.Mesh
    Mesh_treePineSnow_1: THREE.Mesh
    Mesh_treePineSnow_2: THREE.Mesh
  }
  materials: {
    snow: THREE.MeshStandardMaterial
    leaves: THREE.MeshStandardMaterial
    wood: THREE.MeshStandardMaterial
  }
}

export function TreeHolidayPineSnow(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/treeHolidayPineSnow.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_treePineSnow.geometry} material={materials.snow} />
      <mesh geometry={nodes.Mesh_treePineSnow_1.geometry} material={materials.leaves} />
      <mesh geometry={nodes.Mesh_treePineSnow_2.geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/treeHolidayPineSnow.glb')
