/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 blockSnowSlopeHalf.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { snow } from "./materials";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_blockSnowSlopeHalf: THREE.Mesh;
    Mesh_blockSnowSlopeHalf_1: THREE.Mesh;
  };
  materials: {
    snow: THREE.MeshStandardMaterial;
    dirt: THREE.MeshStandardMaterial;
  };
};

export function BlockSnowSlopeHalf(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("blockSnowSlopeHalf.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_blockSnowSlopeHalf.geometry} material={snow} />
      <mesh
        geometry={nodes.Mesh_blockSnowSlopeHalf_1.geometry}
        material={materials.dirt}
      />
    </group>
  );
}

useGLTF.preload("blockSnowSlopeHalf.glb");
