/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 fox.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {};
  materials: {};
};

export function Fox(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/fox.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group />
    </group>
  );
}

useGLTF.preload("/fox.glb");
