/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ski.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ski } from "./materials";

type GLTFResult = GLTF & {
  nodes: {
    ski1: THREE.Mesh;
  };
  materials: {
    initialShadingGroup1: THREE.MeshStandardMaterial;
  };
};

export function Ski(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("ski.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ski1.geometry} material={ski} scale={0.01} />
    </group>
  );
}

useGLTF.preload("ski.glb");
