/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 treePineSnow.glb -t -k
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { snow } from "./materials";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_treePineSnow: THREE.Mesh;
    Mesh_treePineSnow_1: THREE.Mesh;
  };
  materials: {
    dirt: THREE.MeshStandardMaterial;
    snow: THREE.MeshStandardMaterial;
  };
};

export function TreePineSnow(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/treePineSnow.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Mesh_treePineSnow"
        geometry={nodes.Mesh_treePineSnow.geometry}
        material={materials.dirt}
      />
      <mesh
        name="Mesh_treePineSnow_1"
        geometry={nodes.Mesh_treePineSnow_1.geometry}
        material={snow}
      />
    </group>
  );
}

useGLTF.preload("/treePineSnow.glb");
