/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 treeHolidayPine.glb -t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_treePine: THREE.Mesh;
    Mesh_treePine_1: THREE.Mesh;
  };
  materials: {
    wood: THREE.MeshStandardMaterial;
    leaves: THREE.MeshStandardMaterial;
  };
};

export function TreeHolidayPine(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("treeHolidayPine.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_treePine.geometry} material={materials.wood} />
      <mesh
        geometry={nodes.Mesh_treePine_1.geometry}
        material={materials.leaves}
      />
    </group>
  );
}

useGLTF.preload("treeHolidayPine.glb");
